---
title: "Phylogeny"
author: "JBone"
date: "2025-03-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo=FALSE, root.dir = "/Users/jordanbone/Documents/GitHub/IAV-Mach-Learning/")

# source("MegaLibrary.R")
# install_github("rgriff23/btw")
library(ape)
library(tidyr)
library(stringr)
library(magrittr)

uid_ref <- read.csv("USED UIDS.csv")
# m1_root <- read.nexus("iqtree/alpha iqtree/M1.nexus")
```

```{r}
m1 <- read.nexus("/Users/jordanbone/Documents/Coding_Ref/Phylogenetics/BayesTraits/M1.nexus")
data.frame(m1$edge.length) %>% ggplot(aes(m1.edge.length,fill=m1.edge.length>0))+ geom_histogram()
data.frame(m1$edge.length) %>% subset(m1.edge.length>0.000003) %>% ggplot(aes(m1.edge.length))+ geom_histogram()
```


# BayesTraits
```{r}
library(btw)
setwd("/Users/jordanbone/Documents/Coding_Ref/Phylogenetics/BayesTraits")
read.nexus("IAV/HA.treefile")
```

# ape::ace()
```{r, include=FALSE}
### For discrete characters:
# x <- ifelse(m1_root$tip.label %>% str_split_i("_",3)=="Avian",0,1) %>% as.factor
y <- m1_root$tip.label %>% str_split_i("_",3) %>% as.factor
ans <- ace(y, phy=m1_root,type="discrete")

### Some random data...
data(bird.orders)
x <- rnorm(23)
### Compare the three methods for continuous characters:
ace(x, bird.orders)
ace(x, bird.orders, method = "pic")
ace(x, bird.orders, method = "GLS", corStruct = corBrownian(1, bird.orders))
### For discrete characters:
x <- factor(c(rep(0, 5), rep(1, 18)))
ans <- ace(x, bird.orders, type = "d")
#### Showing the likelihoods on each node:
plot(bird.orders, type = "c", FALSE, label.offset = 1)
co <- c("blue", "yellow")
tiplabels(pch = 22, bg = co[as.numeric(x)], cex = 2, adj = 1)
nodelabels(thermo = ans$lik.anc, piecol = co, cex = 0.75)
```

# PhyTools

```{r, include=FALSE}
library(phytools)
library(phangorn)
library(phylotools)

grass.align <- read.phyDat("grass_aligned-renamed.fasta", format = "fasta")
dist <- dist.ml(grass.align)
nj.tree <- nj(dist)
fit <- pml(nj.tree, data = grass.align)
fitGTR.G <- update(fit, model = "GTR", k = 4)
fitGTR.G <- optim.pml(fitGTR.G, model = "GTR", optGamma = T, rearrangement = "stochastic", control = pml.control(trace = 0))

fitGTR.G$tree <- root(fit$tree, outgroup = c('barley_D-hordein','Siberian wild rye_D-hordein'))
plot(fitGTR.G)
anc.ml <- ancestral.pml(fitGTR.G, "ml")
plotAnc(fitGTR.G$tree, anc.ml, 209)
```

## Continuous 
```{r}
#install.packages('phytools')
library(phytools)

g.tree <- read.nexus('/Users/jordanbone/Documents/GitHub/IAV-Mach-Learning/Phylogenies/iqtree/trees/NEXUS/M1_alignment.nexus')
tree.root <- root(g.tree, outgroup = 'GNY411XNI_ABF69261_Avian_2001')
plot(tree.root)

new <- drop.tip(tree.root, c('barley_D-hordein', 'Siberian_wild_rye_D-hordein', 'Asiatic_grass'),
                trim.internal = TRUE, subtree = FALSE, root.edge = 0, 
                rooted = is.rooted(tree.root), collapse.singles = TRUE, interactive = FALSE)

plot(new)
nodelabels()
new$tip.label
height <- as.numeric(c(24, 36, 20, 30, 48, 18, 78, 60, 48, 48))
anc.height <- fastAnc(new, height, CI = TRUE)
anc.height
```

## Discrete
```{r}
new <- as.phylo(new)

pheno <- read.table('grass_discrete.txt', row.names = 1)
pheno <- as.matrix(pheno)[,1]
pheno
ace(x = pheno, phy = new, type = "discrete", model = "ER")
fit.discrete<-ace(pheno, new, model="ER",type="discrete")
fit.discrete
fit.discrete$lik.anc

plot(new)

cols <- c('blue', 'orange')

nodelabels(node=1:new$Nnode+Ntip(new),pie=fit.discrete$lik.anc,piecol=cols,cex=0.7)

tiplabels(pie=to.matrix(pheno,sort(unique(pheno))),piecol=cols,cex=0.3)

add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1], y=-max(nodeHeights(new)),fsize=0.8)
```


# ggtree
```{r, include=FALSE}
tree <- read.nexus("iqtree/IAV/HA_1.nexus")
anno <- read.csv("iqtree/IAV/HA_anno.tsv",sep="\t")

# groupInfo <- split(tree$tip.label, gsub("_\\w+", "", tree$tip.label))
# groupInfo <- split(tree$tip.label, str_split_i(tree$tip.label,"\\_",3))
chiroptera <- groupOTU(tree, anno)

ggtree(chiroptera,aes(colour=group))+geom_nodelab(aes(label = node), hjust = -0.5)
ggtree(extract.clade(tree, 2727))+geom_nodelab(aes(label = node), hjust = -0.5)
```

# PhylogeneticEM
```{r, include=FALSE}
library(PhylogeneticEM)
library(TreeSim)
set.seed(17920902)
ntaxa = 80
tree <- TreeSim::sim.bd.taxa.age(n = ntaxa, numbsim = 1, lambda = 0.1, mu = 0,
                                 age = 1, mrca = TRUE)[[1]]

params <- params_process("OU",                             ## Process
                         p = 2,                            ## Dimension
                         variance = diag(0.5, 2, 2) + 0.5, ## Rate matrix
                         selection.strength = 3,           ## Selection Strength
                         random = TRUE,                    ## Root is random
                         stationary.root = TRUE,           ## Root is stationary
                         edges = c(16, 81, 124),           ## Positions of the shifts
                         values = cbind(c(5, 4),           ## Values of the shifts
                                        c(-4, -5),
                                        c(5, -3)))
plot(params, phylo = tree, traits = 1, value_in_box = TRUE, shifts_bg = "white")
plot(params, phylo = tree, traits = 2, value_in_box = TRUE, shifts_bg = "white")

sim <- simul_process(params, tree)

data <- extract(sim,             ## The simul_process object
                what = "states", ## We want the actual values
                where = "tips")  ## Only at the tips of the tree

rownames(data) <- c("A", "B")

plot(params, phylo = tree, data = data)
```

## Inference
```{r, include=FALSE}
res <- PhyloEM(phylo = tree,
               Y_data = data,
               process = "scOU",                   ## scalar OU model
               random.root = TRUE,                 ## Root is stationary (true model)
               stationary.root = TRUE,
               alpha = alpha_grid,                 ## On a grid of alpha
               K_max = 10,                         ## Maximal number of shifts
               parallel_alpha = TRUE,              ## This can be set to TRUE for
               Ncores = 2)                         ## parallel computations
res
plot(res)
plot_criterion(res)
plot(res, params = params_process(res, method.selection = "DDSE"))
plot(res, params = params_process(res, K = 3, alpha = 1))

params_process(res, K = 3, alpha = 1)$shifts
params_process(res, K = 3, alpha = 3)$shifts

```
